#!/bin/sh
# -*- sh -*-
# Plugin to plot powerhaus values.
#
#%# family=contrib

if [ "$1" = "autoconf" ]; then
	echo no
	exit 0
fi

if [ "$1" = "config" ]; then
        echo 'graph_title Power usage'
        echo 'graph_info Raw numbers from powerhaus sensor.'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel Umps'
        echo 'graph_category sensors'
	for i in `seq 0 4`; do
		echo "ct$i.label ct$i"
		echo "ct$i.type GAUGE"
	done
	for i in `seq 0 4`; do
		echo "p$i.label p$i"
		echo "p$i.type GAUGE"
	done
        exit 0
fi

cat /var/tmp/powerhaus.munin.txt
